import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import axios from "axios";
import { Card, Spinner, Alert, Table, Button } from "react-bootstrap";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function ViewEmployee() {

    const { eid } = useParams();
    const navigate = useNavigate();

    const [employee, setEmployee] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {

        axios
            .get(`http://localhost:8080/employee/getEmployeeById/${eid}`)
            .then((response) => {

                setEmployee(response.data);
                setLoading(false);

            })
            .catch((error) => {

                console.error(error);
                setLoading(false);

            });

    }, [eid]);

    const exportPDF = () => {

        const doc = new jsPDF();

        doc.setFontSize(20);
        doc.text("SpringWave Technologies", 55, 15);

        doc.setFontSize(16);
        doc.text("Employee Details Report", 60, 25);

        autoTable(doc, {
            startY: 35,
            head: [["Field", "Value"]],
            body: [
                ["Employee ID", employee.eid],
                ["Name", employee.name],
                ["Address", employee.address],
                ["Salary", employee.salary],
                ["Email", employee.email],
                ["Phone", employee.phone],
                ["Department", employee.department],
                ["Designation", employee.designation],
                ["Date Of Joining", employee.dateOfJoining],
                ["Date Of Birth", employee.dateOfBirth],
                ["Gender", employee.gender],
                ["Marital Status", employee.maritalStatus],
                ["Blood Group", employee.bloodGroup],
                ["Password", employee.password]
            ]
        });

        doc.text(
            "Generated by Employee Management System",
            50,
            doc.lastAutoTable.finalY + 20
        );

        doc.save(`Employee_${employee.eid}.pdf`);
    };

    if (loading) {
        return (
            <div className="text-center mt-5">
                <Spinner animation="border" />
            </div>
        );
    }

    if (!employee) {
        return (
            <Alert variant="danger">
                Employee Not Found
            </Alert>
        );
    }

    return (

        <Card className="shadow mt-4">

            <Card.Header className="bg-primary text-white text-center">
                <h2>Employee Details</h2>
            </Card.Header>

            <Card.Body>

                <Table bordered hover>

                    <tbody>

                        <tr>
                            <th>Employee ID</th>
                            <td>{employee.eid}</td>
                        </tr>

                        <tr>
                            <th>Name</th>
                            <td>{employee.name}</td>
                        </tr>

                        <tr>
                            <th>Address</th>
                            <td>{employee.address}</td>
                        </tr>

                        <tr>
                            <th>Salary</th>
                            <td>{employee.salary}</td>
                        </tr>

                        <tr>
                            <th>Email</th>
                            <td>{employee.email}</td>
                        </tr>

                        <tr>
                            <th>Phone</th>
                            <td>{employee.phone}</td>
                        </tr>

                        <tr>
                            <th>Department</th>
                            <td>{employee.department}</td>
                        </tr>

                        <tr>
                            <th>Designation</th>
                            <td>{employee.designation}</td>
                        </tr>

                        <tr>
                            <th>Date Of Joining</th>
                            <td>{employee.dateOfJoining}</td>
                        </tr>

                        <tr>
                            <th>Date Of Birth</th>
                            <td>{employee.dateOfBirth}</td>
                        </tr>

                        <tr>
                            <th>Gender</th>
                            <td>{employee.gender}</td>
                        </tr>

                        <tr>
                            <th>Marital Status</th>
                            <td>{employee.maritalStatus}</td>
                        </tr>

                        <tr>
                            <th>Blood Group</th>
                            <td>{employee.bloodGroup}</td>
                        </tr>

                        <tr>
                            <th>Password</th>
                            <td>{employee.password}</td>
                        </tr>


                    </tbody>

                </Table>

                <div className="text-center mt-4">

                    <Button
                        variant="danger"
                        className="me-3"
                        onClick={exportPDF}
                    >
                        Export PDF
                    </Button>

                    <Button
                        variant="secondary"
                        onClick={() => navigate("/employeeList")}
                    >
                        Back
                    </Button>

                </div>

            </Card.Body>

        </Card>

    );
}

export default ViewEmployee;